### ISSUE TITLE
Old version numbering is perceived as latest release

### ISSUE THREAD

**Issue by zhang-alvin** [conda-forge/scorec-feedstock#3]
Issue:

When no version number is specified for installation, the latest version is downloaded. In this case, that corresponds to version 20161004 and not the more recent v2.2.2.  

```
  added / updated specs:
    - scorec=2.2.2


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    scorec-2.2.2               |mpi_mpich_h9f7b9cf_0        10.7 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        10.7 MB

The following packages will be DOWNGRADED:

  scorec                      20161004-mpi_mpich_h9f7b9cf_1 --> 2.2.2-mpi_mpich_h9f7b9cf_0

```
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : proteus-dev
    active env location : /home/zhanga/miniconda3/envs/proteus-dev
            shell level : 1
       user config file : /home/zhanga/.condarc
 populated config files : /home/zhanga/.condarc
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages : 
       base environment : /home/zhanga/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/zhanga/miniconda3/pkgs
                          /home/zhanga/.conda/pkgs
       envs directories : /home/zhanga/miniconda3/envs
                          /home/zhanga/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Linux/5.3.0-19-generic linuxmint/19 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


```
</details>

**Comment by davidbrochart** [comment]
I think this is because the first version available for scorec in conda-forge didn't use semver semantic versioning. But if we interpret it according to semver, indeed `20161004` > `2.2.2`! I will tag `20161004` as broken.
Thanks!

**Comment by davidbrochart** [comment]
The following build artifacts are broken (they are not semver-based):

`osx-64/scorec-20161004-mpi_mpich_hbc1d92b_1.tar.bz2`
`osx-64/scorec-20161004-mpi_openmpi_hdba7654_1.tar.bz2`
`linux-64/scorec-20161004-mpi_openmpi_hc401efc_1.tar.bz2`
`linux-64/scorec-20161004-mpi_mpich_h9f7b9cf_1.tar.bz2`
`osx-64/scorec-20161004-mpi_mpich_hbc1d92b_0.tar.bz2`
`osx-64/scorec-20161004-mpi_openmpi_hdba7654_0.tar.bz2`
`linux-64/scorec-20161004-mpi_openmpi_hc401efc_0.tar.bz2`
`linux-64/scorec-20161004-mpi_mpich_h9f7b9cf_0.tar.bz2`

Would it be possible to tag them as "broken" on anaconda.org?

cc @conda-forge/core

**Comment by isuruf** [comment]
See https://github.com/conda-forge/cf-mark-broken

**Comment by davidbrochart** [comment]
Done in https://github.com/conda-forge/cf-mark-broken/pull/3
